"""
JOBS/TRADER/STRATEGY/AI.PY
==============================================================================
MODULE: AI CONSULTATION (Gattaca Integration) 🤖
PURPOSE: Consult Gattaca AI for trading decisions.
==============================================================================
"""

from typing import Dict, Optional, Tuple
from loguru import logger

from pydantic import BaseModel, Field
from jobs.trader.config import TraderConfig
from jobs.trader.strategy.signals import Signal


class ValidationDecision(BaseModel):
    decision: str = Field(..., description="APPROVE, REJECT, or NEUTRAL")
    reason: str = Field(..., description="Brief reason for the decision")
    confidence_modifier: float = Field(..., description="Modifier from -10.0 to +10.0")


async def consult_ai(
    pair: str, indicators: Dict, current_signal: Signal, config: TraderConfig = None
) -> Tuple[bool, str, float]:
    """
    Consult Gattaca AI for trading validation.

    Args:
        pair: Trading pair
        indicators: Technical indicators from brain.evaluate()
        current_signal: Signal generated by brain
        config: Runtime configuration

    Returns:
        (approved, reason, confidence_modifier)
    """
    config = config or TraderConfig.load()

    # Skip if AI not enabled
    if not config.ai_enabled:
        return True, "AI disabled", 0.0

    try:
        from corpus.brain.gattaca import gattaca

        # Build context for AI
        context = _build_ai_context(pair, indicators, current_signal)

        # Query AI via Gattaca route 2 (REFLEX - fast responses)
        # SOTA 2026: Strict JSON Output
        response_json = await gattaca.think(
            context, route_id=2, response_schema=ValidationDecision
        )

        try:
            # Depending on Gattaca return, it might be a dict (if parsed) or text (if not)
            # Gattaca _route_text usually returns text, but with response_schema
            # the SDK returns a json string that we need to parse, OR gattaca handles it?
            # Looking at gattaca.py: return response.text or ""
            # So we get transparency JSON string.
            import json

            if isinstance(response_json, str):
                # Clean markdown blocks if present
                clean = response_json.replace("```json", "").replace("```", "").strip()
                data = json.loads(clean)
                decision_obj = ValidationDecision(**data)
            else:
                # Should not happen unless gattaca changed
                decision_obj = ValidationDecision(**response_json)

            return (
                decision_obj.decision == "APPROVE",
                decision_obj.reason,
                decision_obj.confidence_modifier,
            )

        except Exception as e:
            logger.error(f"🤖 [AI] Parsing error: {e}")
            # Fallback safe: Neutral
            return True, "AI output invalid", 0.0

    except ImportError:
        logger.warning("🤖 [AI] Gattaca not available")
        return True, "Gattaca unavailable", 0.0
    except Exception as e:
        logger.error(f"🤖 [AI] Consultation error: {e}")
        return True, f"AI error: {e}", 0.0


def _build_ai_context(pair: str, indicators: Dict, signal: Signal) -> str:
    """Build context prompt for AI."""
    return f"""
TRADING DECISION VALIDATION

Pair: {pair}
Signal: {signal.action}
Confidence: {signal.confidence:.1f}%
Reason: {signal.reason}

Technical Indicators:
- RSI: {indicators.get("rsi", 50):.1f}
- MACD: {indicators.get("macd", 0):.4f}
- BB Position: {indicators.get("bb_position", 0.5):.2f}
- ATR%: {indicators.get("atr_pct", 0):.2f}%
- Trend: {"Bullish" if indicators.get("is_uptrend") else "Bearish"}
- In Fib Zone: {indicators.get("in_fib_zone", False)}
- Volume Ratio: {indicators.get("volume_ratio", 1.0):.1f}x

Should I proceed with this {signal.action} signal?
Reply with: APPROVE, REJECT, or NEUTRAL (with reason and confidence modifier -10 to +10).
"""


# _parse_ai_response REMOVED (Obsolete)


async def get_ai_market_sentiment() -> Dict:
    """
    Get AI's overall market sentiment.

    Returns:
        {sentiment, confidence, reasoning}
    """
    try:
        from corpus.brain.gattaca import gattaca

        response = await gattaca.think(
            "What is the current crypto market sentiment? Reply: BULLISH/BEARISH/NEUTRAL with confidence 0-100 and brief reasoning.",
            route_id=gattaca.ROUTE_FLASH,
        )

        # Parse simple response
        sentiment = "NEUTRAL"
        confidence = 50

        if "BULLISH" in response.upper():
            sentiment = "BULLISH"
            confidence = 70
        elif "BEARISH" in response.upper():
            sentiment = "BEARISH"
            confidence = 70

        return {
            "sentiment": sentiment,
            "confidence": confidence,
            "reasoning": response[:200],
        }
    except Exception as e:
        logger.error(f"🤖 [AI] Sentiment error: {e}")
        return {"sentiment": "NEUTRAL", "confidence": 50, "reasoning": "AI unavailable"}


async def ask_for_strategy_recommendation(
    performance: Dict, market_conditions: Dict = None
) -> Optional[str]:
    """
    Ask AI for strategy recommendation (sniper vs mitraillette).

    Args:
        performance: Recent performance stats
        market_conditions: Current market data

    Returns:
        Recommended mode or None
    """
    try:
        from corpus.brain.gattaca import gattaca

        prompt = f"""
Based on recent performance:
- Win Rate: {performance.get("win_rate", 0):.1f}%
- Total PnL: {performance.get("total_pnl", 0):.2f}€
- Trades: {performance.get("trades", 0)}

Which strategy do you recommend?
- MITRAILLETTE: Fast scalping, many small trades
- SNIPER: Precision, few high-confidence trades

Reply with just: MITRAILLETTE or SNIPER
"""

        response = await gattaca.think(prompt, route_id=2)

        if "SNIPER" in response.upper():
            return "sniper"
        elif "MITRAILLETTE" in response.upper():
            return "mitraillette"

        return None
    except Exception as e:
        logger.error(f"🤖 [AI] Strategy recommendation error: {e}")
        return None


async def ask_for_strategy_switch(
    current_mode: str, new_mode: str, reason: str = ""
) -> bool:
    """
    Ask AI to confirm a strategy switch (Gatekeeper).
    """
    try:
        from corpus.brain.gattaca import gattaca

        prompt = f"""
STRATEGY SWITCH REQUEST
Current Mode: {current_mode}
Proposed Mode: {new_mode}
Reason: {reason}

Should I approve this switch?
Reply with: APPROVE or REJECT
"""
        response = await gattaca.think(prompt, route_id=2)
        return "APPROVE" in response.upper()

    except Exception as e:
        logger.error(f"🤖 [AI] Switch check error: {e}")
        return False
